title: "Laura Contreras-Portela"
author: "Laura Contreras-Portela"
description: "Aix-Marseille School of Economics"
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: "Home"}
  - {file: "research.md" , title: "Research"}
  - {url: "contreras_CV.pdf", title: "CV"}
  - {file: "teaching.md" , title: "Teaching"}
  - {file: "resources.md" , title: "Resources"}
  - {file: "blog.md" , title: "Blog"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:laura.contreras-portela.univ-amu.fr"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/contreraaaaas"}
comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

theme: minima
minima:
  # Minima skin selection.
  # Available skins are:
  # classic	           Default, light color scheme.
  # dark	             Dark variant of the classic skin.
  # auto	             Adaptive skin based on the default classic and dark skins.
  # solarized-light	   Light variant of solarized color scheme.
  # solarized-dark	   Dark variant of solarized color scheme.
  # solarized	         Adaptive skin for solarized color scheme skins.
  skin: classic

plugins:
 - jekyll-feed
